language: node_js #指定运行环境
node_js:
  # - '12'
  - '10'
  - '8'
  # - '6'
  # - '4'

install:
  - npm install --save-dev jest
  - npm install coveralls --save-dev

cache:
  directories: node_modules #缓存node_modules文件

script:
  - npm run coveralls
  
after_script:
  - cd ./public
  - git init
  - git config user.name "WangJuYan"
  - git config user.email "1411460132@qq.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${github_token}@${GH_REF}" master:travis_test #静态页面放在dev分支
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken IpUW3kFRlfOij9cYPGF82SmJFz1q9Bbgx

branches:
  only:
    - master #触发持续集成的分支

env:
  global:
    - GH_REF: github.com/WangJuYan/wjyTest.git    #仓库地址

os: osx