language: node_js #指定运行环境
node_js:
  # - '12'
  # - '10'
  - '8'
  # - '6'
  # - '4'

install:
  # - npm install
  - npm install --save-dev jest
  - npm install coveralls --save-dev

cache:
  directories:
  - node_modules #缓存node_modules文件

# after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken dvI1LR7V4h9gLMMp25pWAIhpDdUjTkfW9

after_success:
  - npm run coveralls

# script:
#   - npm run coveralls

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken dvI1LR7V4h9gLMMp25pWAIhpDdUjTkfW9
      # script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

os: osx