language: node_js #指定运行环境
node_js:
  # - '12'
  # - '10'
  - '8'
  # - '6'
  # - '4'

install:
  # - npm install
  - npm install --save-dev jest
  - npm install coveralls --save-dev

cache:
  directories:
  - node_modules #缓存node_modules文件

script:
  - npm run coveralls
  - jest coveralls

after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken dvI1LR7V4h9gLMMp25pWAIhpDdUjTkfW9

os: osx