language: node_js #指定运行环境
node_js:
  # - '12'
  # - '10'
  - '8'
  # - '6'
  # - '4'

install:
  - npm install --save-dev jest
  - npm install coveralls --save-dev

cache:
  directories: node_modules #缓存node_modules文件

script:
  - npm run coveralls
  # - npm run test --coverage
  # 没有全局安装 codecov，所以要通过 npm 来运行 codecov
  # - npm run codecov

after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken 7cRO6F7KccTCqDdDtXctp4aXnqveU8OqU

os: osx