language: node_js #指定运行环境
node_js: node
  # - '12'
  # - '10'
  # - '8'
  # - '6'
  # - '4'

install:
  - npm install --save-dev jest
  - npm install coveralls --save-dev

  # - yarn global add jest
  # - yarn global add coveralls

# cache: yarn

cache:
  directories: node_modules, #缓存node_modules文件

script:
  # - jest --coverage --coverageReporters=text-lcov | coveralls
  # - jest --coverage
  # - npm run coveralls
  # - npm run test --coverage
  # 没有全局安装 codecov，所以要通过 npm 来运行 codecov
  # - npm run codecov

after_script:
  - cd ./public
  - git init
  - git config user.name "WangJuYan"
  - git config user.email "1411460132@qq.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${github_token}@${GH_REF}" master:travis_test #静态页面放在dev分支
  # - git push --force --quiet "https://${GH_TOKEN}@${你得项目地址(如果源码跟发布的不在一个分支 这里是分发布用的分支地址)，不带https}" master:master
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken 7cRO6F7KccTCqDdDtXctp4aXnqveU8OqU

# after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js -repotoken 7cRO6F7KccTCqDdDtXctp4aXnqveU8OqU

branches:
  only:
    - master #触发持续集成的分支

env:
  global:
    - GH_REF: github.com/WangJuYan/wjyTest.git    #仓库地址

os: osx