language: node_js
node_js:
  # - '12'
  # - '10'
  # - '8'
  # - '6'
  # - '4'
  - '0.12'
  # - '0.10'`
after_script:
  - npm run coveralls

# cache:
#   directories:
#   - node_modules

# install:
#   - npm install
#   - npm global add node-coveralls


# script:
# - jest --coverage --coverageReporters=text-lcov | coveralls


# os: osx

# # Create the keychain with a password
# security create-keychain -p travis ios-build.keychain

# # Make the custom keychain default, so xcodebuild will use it for signing
# security default-keychain -s ios-build.keychain

# # Unlock the keychain
# security unlock-keychain -p travis ios-build.keychain

# # Add certificates to keychain and allow codesign to access them
# security import ./Provisioning/certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
# security import ./Provisioning/certs/distribution.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
# security import ./Provisioning/certs/distribution.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign

# security set-key-partition-list -S apple-tool:,apple: -s -k travis ios-build.keychain