language: node_js
node_js:
  # - '12'
  # - '10'
  # - '8'
  # - '6'
  # - '4'
  - '0.12'
  # - '0.10'`

before_install:
  - npm install coveralls --save-dev

install:
  - npm install
  - npm global add node-coveralls

cache: npm
  # directories:
  # - node_modules

script:
  - npm run coveralls
# - jest --coverage --coverageReporters=text-lcov | coveralls

after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken UyKJQZqkioZqmDyrvFz6YWaqwQ9XaA3t0 

# after_success:
#   - npm run coveralls

os: osx